import FormStepProvider from "@/provider/FormStepProvider";
import PropertyProvider from "@/provider/PropertyProvider";
import ValidFormProvider from "@/provider/ValidFormProvider";
import type { Metadata } from "next";
import { Fustat } from "next/font/google";
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";

const fustat = Fustat({
  variable: "--font-fustat",
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${fustat.variable} antialiased`}>
        <FormStepProvider>
          <ValidFormProvider>
            <PropertyProvider>
              <Header />
              {children}
              <Footer />
            </PropertyProvider>
          </ValidFormProvider>
        </FormStepProvider>
      </body>
    </html>
  );
}
